[package]
name = "rustray"
version = "0.1.0"
authors = ["Christian Iversen <ci@iversenit.dk>"]

[features]
default = ["self_shadowing", "antialias"]
self_shadowing = []
antialias = []

[dependencies]
image = "0.23.8"
num = "0.3.0"
rand = "0.7.3"
indicatif = "0.15.0"
colog = "1.0.0"
log = "0.4.11"
