[package]
name = "rustray"
version = "0.1.0"
authors = ["Christian Iversen <ci@iversenit.dk>"]
edition = "2021"

[features]
default = ["self_shadowing", "antialias"]
self_shadowing = []
antialias = []

[dependencies]
image = "0.23.8"
num = "0.4.0"
num-traits = "0.2.14"
rand = "0.8.4"
indicatif = { version = "0.16.2", features = ["rayon"] }
colog = "1.0.0"
log = "0.4.11"
rayon = "*"
obj = { version = "0.10", features = ["genmesh"] }
genmesh = "0.6"
bvh = "0.6"
