[package]
name = "rustray"
version = "0.1.0"
authors = ["Christian Iversen <ci@iversenit.dk>"]

[features]
default = ["self_shadowing", "antialias"]
self_shadowing = []
antialias = []

[dependencies]
image = "0.21"
num = "0.2"
rand = "0.6.5"
indicatif = ""
colog = "0.2"
log = ""